### ISSUE TITLE
Provide a generic mechanism for configuring different ConfigSources

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#104]
The `@app-config/config` module has a loading strategy baked-in. It would be awesome to describe that strategy "declaratively". This way, we can enable choosing different ConfgSources via the meta file.

**Comment by joelgallant** [comment]
Pseudo-code

```
FallbackSource:
  - EnvironmentSource:
    - APP_CONFIG
  - CombineSources
    - FlexibleFileSource: .app-config.secrets.{env}.{ext}:
    - FlexibleFileSource: .app-config.secrets.{ext}
    - FlexibleFileSource: .app-config.{env}.{ext}:
    - FlexibleFileSource: .app-config.{ext}
```

There are some obvious questions here like default values, "merge/combine" strategies with secret files, and parsing extension settings.
