### ISSUE TITLE
Add support for a "CLI Config Source" (parse command line options)

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#43]
A common thread in config libraries in other ecosystems is the ability to use CLI args as an augmentation / override. I think supporting a simple set of CLI flag types is basically in-line with app config. This may make sense as a separate NPM package, however. I'm fairly convinced that encryption and others will end up as separate packages at some point anyway.

**Comment by joelgallant** [comment]
Simple pseudo-code from prototyping:

```yaml
# this would merge all properties from CLI yargs parsed object
$yargs: true

# this would pull --foo=... option
$yargs: foo
```

Maybe `$loadYargs` like #142.
